# Generated by Django 5.0.2 on 2025-05-19 02:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='NombreDesconocido', max_length=100)),
                ('apellido', models.CharField(default='ApellidoDesconocido', max_length=100)),
                ('fecha_nacimiento', models.DateField(default='1990-01-01')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'Prefiero no decirlo')], default='N', max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('numero_celular', models.CharField(default='0000000000', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('conejo', 'Conejo'), ('otro', 'Otro')], max_length=20)),
                ('otra_especie', models.CharField(blank=True, max_length=100)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('unidad_edad', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('desconocido', 'No lo sé')], max_length=20)),
                ('color_principal', models.CharField(blank=True, max_length=50)),
                ('caracteristicas_especiales', models.TextField(blank=True)),
                ('fecha_perdida', models.DateField(blank=True, null=True)),
                ('lugar_perdida', models.CharField(blank=True, max_length=255)),
                ('ultima_vez', models.TextField(blank=True)),
                ('telefono', models.CharField(max_length=20)),
                ('notas_adicionales', models.TextField(blank=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='mascotas_fotos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MascotaAdopcion',
            fields=[
                ('id_mascota_adopcion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=20)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('edad', models.CharField(max_length=50)),
                ('tamanio', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('vacunado', models.BooleanField(default=False)),
                ('esterilizado', models.BooleanField(default=False)),
                ('amigableConMascotas', models.BooleanField(default=False)),
                ('amigableConNinos', models.BooleanField(default=False)),
                ('necesidadesEspeciales', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas_adopcion_fotos/')),
                ('contactoNombre', models.CharField(max_length=100)),
                ('contactoEmail', models.EmailField(max_length=254)),
                ('contactoTelefono', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_adopcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id_adopcion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to=settings.AUTH_USER_MODEL)),
                ('mascota_adopcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='api.mascotaadopcion')),
            ],
        ),
        migrations.CreateModel(
            name='MascotaEncontrada',
            fields=[
                ('id_mascota_encontrada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('D', 'Desconocido')], max_length=1)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('tamaño', models.CharField(blank=True, max_length=50)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ultima_ubicacion', models.CharField(blank=True, max_length=255)),
                ('fecha_encontrada', models.DateField(blank=True, null=True)),
                ('senas_particulares', models.TextField(blank=True)),
                ('estado_publicacion', models.CharField(choices=[('encontrado', 'Encontrado'), ('adopcion', 'En adopción'), ('otro', 'Otro')], max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('recompensa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='mascotas_encontradas_fotos/')),
                ('id_adopcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas_encontradas', to='api.adopcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_encontradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adopcion',
            name='mascota_encontrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='api.mascotaencontrada'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('adopcion', 'Adopción'), ('busqueda', 'Búsqueda'), ('encontrada', 'Mascota Encontrada')], max_length=20)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('finalizado', 'Finalizado')], default='vigente', max_length=20)),
                ('contenido', models.TextField()),
                ('reacciones', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('mascotas', models.ManyToManyField(blank=True, related_name='publicaciones', to='api.mascota')),
                ('mascotas_adopcion', models.ManyToManyField(blank=True, related_name='publicaciones_adopcion', to='api.mascotaadopcion')),
                ('mascotas_encontradas', models.ManyToManyField(blank=True, related_name='publicaciones_encontradas', to='api.mascotaencontrada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id_reaccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='me_encanta', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones_obj', to='api.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
    ]
