# Generated by Django 5.0.2 on 2025-05-11 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('D', 'Desconocido')], max_length=1)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('tamaño', models.CharField(blank=True, max_length=50)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ultima_ubicacion', models.CharField(blank=True, max_length=255)),
                ('fecha_perdida', models.DateField(blank=True, null=True)),
                ('senas_particulares', models.TextField(blank=True)),
                ('estado_publicacion', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado'), ('adopcion', 'En adopción'), ('otro', 'Otro')], max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('recompensa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='mascotas_fotos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
