# Generated by Django 5.0.2 on 2025-05-11 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id_adopcion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MascotaEncontrada',
            fields=[
                ('id_mascota_encontrada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('D', 'Desconocido')], max_length=1)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('tamaño', models.CharField(blank=True, max_length=50)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ultima_ubicacion', models.CharField(blank=True, max_length=255)),
                ('fecha_encontrada', models.DateField(blank=True, null=True)),
                ('senas_particulares', models.TextField(blank=True)),
                ('estado_publicacion', models.CharField(choices=[('encontrado', 'Encontrado'), ('adopcion', 'En adopción'), ('otro', 'Otro')], max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('recompensa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='mascotas_encontradas_fotos/')),
                ('id_adopcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas_encontradas', to='api.adopcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_encontradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adopcion',
            name='mascota_encontrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='api.mascotaencontrada'),
        ),
    ]
