# Generated by Django 5.0.2 on 2025-05-11 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adopcion_mascotaencontrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('adopcion', 'Adopción'), ('busqueda', 'Búsqueda'), ('encontrada', 'Mascota Encontrada')], max_length=20)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('finalizado', 'Finalizado')], default='vigente', max_length=20)),
                ('contenido', models.TextField()),
                ('reacciones', models.PositiveIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('mascotas', models.ManyToManyField(blank=True, related_name='publicaciones', to='api.mascota')),
                ('mascotas_encontradas', models.ManyToManyField(blank=True, related_name='publicaciones_encontradas', to='api.mascotaencontrada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.publicacion')),
            ],
        ),
    ]
